name: Publish release
on: workflow_dispatch
env:
  XCODE_VERSION: "['14.2', '14.3.1', '15.1', '15.2']"
  TEST_XCODE_VERSION: '15.1'
jobs:
  prepare:
    runs-on: ubuntu-latest
    name: Prepare outputs
    outputs:
      XCODE_VERSIONS_MATRIX: ${{ env.XCODE_VERSION }}
      VERSION: ${{ steps.get-version.outputs.VERSION }}
    steps:
      - uses: actions/checkout@v4
      - name: Compute outputs
        run: |
          echo "XCODE_VERSIONS_MATRIX=${{ env.XCODE_VERSION }}" >> $GITHUB_OUTPUT
      - name: Read SDK version
        id: get-version
        run: |
          version="$(sed -n 's/^VERSION=\(.*\)$/\1/p' "${GITHUB_WORKSPACE}/dependencies.list")"
          echo "VERSION=$version" >> $GITHUB_OUTPUT
  tag-release:
      runs-on: ubuntu-latest
      name: Tag Release
      needs: prepare
      steps:
        - uses: actions/checkout@v4
  publish-docs:
      runs-on: macos-latest
      name: Publish docs to S3 Bucket
      needs: tag-release
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_DOCS_ACCESS_KEY }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_DOCS_SECRET_ACCESS_KEY }}
        GITHUB_ACCESS_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      steps:
        - uses: actions/checkout@v4
        - uses: ruby/setup-ruby@v1
          with:
            bundler-cache: true
        - run: brew install s3cmd
        - name: Publish docs
          run: bundle exec sh -x build.sh publish-docs ${{ github.sha }}
